# Generated by Django 4.0 on 2022-06-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myphone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
